name: pomotimer
description: A simple Pomodoro timer for Android.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  audioplayer: ^0.4.0
  path_provider: ^0.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - sounds/beep.wav
    - sounds/beep2.wav

analyzer:
  language:
    enableStrictCallChecks: true
    enableSuperMixins: true
    enableAssertInitializer: true
  strong-mode:
    implicit-dynamic: false
